from colorama import Fore

print(Fore.GREEN)
repeat = 1
while repeat == 1:
    print("AuthenticationErrrrror")
    print("ERROR")
    print("function Str_result")
    print(" if (!isset($_SESSION['Ul_params']")
    print("  $_SESSION['Ul_params'] = 0;")
    print(" else ")
    print("  if ($_POST['NameUP']) $_SESSION['Ul_params'] = 1;")    
    print("      else if ($_POST['NameDown']) $_SESSION['Ul_params'] = 2;")
    print("  else if ($_POST['PriceUP']) $_SESSION['Ul_params'] = 3;")  
    print("  else if ($_POST['PriceDown']) $_SESSION['Ul_params'] = 4;")  
    print("  else if ($_POST['idUP']) $_SESSION['Ul_params'] = 0;")    
    print("else if ($_POST['idDown']) $_SESSION['Ul_params'] = 5;")    
    print(" if($_SESSION['Ul_params'] == 0) return '`id` ASC';")    
    print(" else if($_SESSION['Ul_params'] == 0) return '`id` ASC';")    
    print("else if($_SESSION['Ul_params'] == 1) return '`name` ASC';")    
    print(" else if($_SESSION['Ul_params'] == 2) return '`name` DESC';")    
    print("else if($_SESSION['Ul_params'] == 3) return '`priceflo` ASC';")    
    print(" else if($_SESSION['Ul_params'] == 4) return '`priceflo` DESC';")    
    print(" else if($_SESSION['Ul_params'] == 5) return '`id` DESC';")    
    print("")    
    print("")    
    print("")    
    print("")    
    print("")    
    print("")
